// <auto-generated/>
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyTitleAttribute("Substance.Collections.Generic")]
[assembly: AssemblyProductAttribute("Substance")]
[assembly: AssemblyDescriptionAttribute("...")]
[assembly: AssemblyVersionAttribute("0.0.2")]
[assembly: AssemblyFileVersionAttribute("0.0.2")]
[assembly: InternalsVisibleToAttribute("Substance.Collections")]
[assembly: InternalsVisibleToAttribute("Substance.Collections.Generic")]
[assembly: InternalsVisibleToAttribute("Substance.Collections.Immutable")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.2";
    }
}
