// <auto-generated/>
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyTitleAttribute("Substance.Collections.Immutable")]
[assembly: AssemblyProductAttribute("Substance")]
[assembly: AssemblyDescriptionAttribute("...")]
[assembly: AssemblyVersionAttribute("1.0")]
[assembly: AssemblyFileVersionAttribute("1.0")]
[assembly: InternalsVisibleToAttribute("Substance.Collections")]
[assembly: InternalsVisibleToAttribute("Substance.Collections.Generic")]
[assembly: InternalsVisibleToAttribute("Substance.Collections.Immutable")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0";
    }
}
